# File: .github/workflows/workflow.yml

on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Build React App
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build --if-present

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLI_CDN }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az account show
            az storage -h
