# File: .github/workflows/workflow.yml

on: [push]

#  workflow_dispatch:

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Copy asset-manifest.json to podlet
        run: cp build/asset-manifest.json podlet/

      - name: Rename main.*.js file
        run: mv build/static/js/main.*.js build/static/js/main.js

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLI_CDN }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            echo ${{ github.event.repository.name }}
            az storage blob upload \
              --file "build/$file" \
              --container-name "alpha/fint-kontroll-appbar-pod" \
              --account-name stflaiscdn \
              --name main.js \
              --overwrite
