
on: [push]

#  workflow_dispatch:

name: Podlet build and deploy

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Copy asset-manifest.json to podlet
        run: cp build/asset-manifest.json podlet/

      - name: Rename main.*.js file
        run: mv build/static/js/main.*.js build/static/js/main.js

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLI_CDN }}

      - name: Upload assets to CDN
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az storage blob upload \
              --file "build/static/js/main.js" \
              --container-name "alpha/${{ github.event.repository.name }}" \
              --account-name stflaiscdn \
              --name main.js \
              --overwrite

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
