# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Build React App
      - run: yarn build

      - name: Copy asset-manifest.json to podlet
        run: cp build/asset-manifest.json podlet/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLI_CDN }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az account show
            az storage -h
